#!/bin/bash
set -eu

readonly IMAGE_REPOSITORY="ghcr.io/kihachi2000/neovim-container"
readonly IMAGE_TAG="${NVIM_CONTAINER_TAG:-latest}"
readonly IMAGE="${NVIM_CONTAINER_IMAGE:-${IMAGE_REPOSITORY}:${IMAGE_TAG}}"

declare -a DOCKER_OPTIONS=(
  "--rm"
  "-u" "$(id -u):$(id -g)"
  "-v" "${PWD}:${PWD}"
  "-w" "${PWD}"
)

# Add -it when running interactively.
if [ -t 0 ] && [ -t 1 ]; then
  DOCKER_OPTIONS+=("-it")
fi

exec wslc.exe run "${DOCKER_OPTIONS[@]}" "${IMAGE}" "$@"
