#!/bin/bash
set -eu

readonly IMAGE="${NVIM_CONTAINER_IMAGE:-ghcr.io/kihachi2000/neovim-container:latest}"

declare -a DOCKER_OPTIONS=(
  "--rm"
  "--entrypoint" "bash"
  "-u" "$(id -u):$(id -g)"
  "-v" "${PWD}:${PWD}"
  "-w" "${PWD}"
)

# Add -it when running interactively.
if [ -t 0 ] && [ -t 1 ]; then
  DOCKER_OPTIONS+=("-it")
fi

exec wslc.exe run "${DOCKER_OPTIONS[@]}" "${IMAGE}" "$@"
