#!/bin/bash
set -eu

readonly IMAGE_REPOSITORY="ghcr.io/kihachi2000/neovim-container"
readonly IMAGE_TAG="${NVIM_CONTAINER_TAG:-latest}"
readonly IMAGE="${NVIM_CONTAINER_IMAGE:-${IMAGE_REPOSITORY}:${IMAGE_TAG}}"

declare -a DOCKER_OPTIONS=(
  "--rm"
  "-v" "${PWD}:${PWD}"
  "-w" "${PWD}"
)

# Change the user ID for non-Mac devices.
if [ "$(uname -s)" != "Darwin" ]; then
  DOCKER_OPTIONS+=("-u" "$(id -u):$(id -g)")
fi

# Add -it when running interactively.
if [ -t 0 ] && [ -t 1 ]; then
  DOCKER_OPTIONS+=("-it")
fi

exec docker run "${DOCKER_OPTIONS[@]}" "${IMAGE}" "$@"
