#!/bin/bash
set -eu

readonly IMAGE="${NVIM_CONTAINER_IMAGE:-ghcr.io/kihachi2000/neovim-container:latest}"

declare -a DOCKER_OPTIONS=(
  "--rm"
  "--entrypoint" "bash"
  "-v" "${PWD}:${PWD}"
  "-w" "${PWD}"
)

# Change the user ID for non-Mac devices.
if [ "$(uname -s)" != "Darwin" ]; then
  DOCKER_OPTIONS+=("-u" "$(id -u):$(id -g)")
fi

# Add -it when running interactively.
if [ -t 0 ] && [ -t 1 ]; then
  DOCKER_OPTIONS+=("-it")
fi

exec docker run "${DOCKER_OPTIONS[@]}" "${IMAGE}" "$@"
